#!/usr/bin/env python3
"""Block pushes and GitHub writes that would publish Claude attribution.

Runs as a Claude Code PreToolUse hook (see .claude/settings.json). It reads the tool
call on stdin and denies it, with the offending line, when:

  * a Bash `git push` would send a commit whose message carries a Claude trailer or
    footer, or whose author/committer is a Claude identity;
  * a GitHub PR / comment / merge call has such text in its title, body or message.

As a PostToolUse hook on PR creation it reminds the model to re-read the new PR,
because the GitHub server can append its own footer after the call.

Only attribution is matched, not the word "Claude" on its own, so code or docs that
talk about Claude (an API integration, say) are not blocked.
"""
import json
import re
import subprocess
import sys

PATTERNS = [
    re.compile(r"co-authored-by:.*(claude|anthropic)", re.I),
    re.compile(r"^claude-session:", re.I | re.M),
    re.compile(r"generated (with|by) \[?claude code", re.I),
    re.compile(r"claude\.ai/code/session_", re.I),
    re.compile(r"noreply@anthropic\.com", re.I),
]
IDENTITY = re.compile(r"^claude\b|anthropic\.com", re.I)


def offending(text: str) -> str | None:
    for pattern in PATTERNS:
        m = pattern.search(text or "")
        if m:
            line_start = text.rfind("\n", 0, m.start()) + 1
            line_end = text.find("\n", m.end())
            return text[line_start:line_end if line_end != -1 else None].strip()
    return None


def deny(reason: str) -> None:
    print(json.dumps({"hookSpecificOutput": {
        "hookEventName": "PreToolUse",
        "permissionDecision": "deny",
        "permissionDecisionReason": reason + " The repository owner does not want Claude "
            "attribution published: remove it (reword the commit with a non-Claude author, "
            "or drop the footer from the text) and try again."}}))
    sys.exit(0)


def unpushed_commits(cwd: str | None) -> list[tuple[str, str, str]]:
    """(sha, identities, message) for every local commit not on any remote branch."""
    fmt = "%H%x1f%an <%ae> / %cn <%ce>%x1f%B%x1e"
    try:
        out = subprocess.run(["git", "log", "--branches", "--not", "--remotes", f"--format={fmt}"],
                             cwd=cwd, capture_output=True, text=True, timeout=20).stdout
    except (OSError, subprocess.SubprocessError):
        return []
    commits = []
    for record in out.split("\x1e"):
        parts = record.strip("\n").split("\x1f")
        if len(parts) == 3:
            commits.append(tuple(parts))
    return commits


def check_push(data: dict) -> None:
    command = data.get("tool_input", {}).get("command", "")
    if not re.search(r"\bgit\b[^;&|]*\bpush\b", command):
        return
    for sha, identities, message in unpushed_commits(data.get("cwd")):
        for who in identities.split(" / "):
            if IDENTITY.search(who):
                deny(f"Commit {sha[:9]} has a Claude author or committer ({who}).")
        line = offending(message)
        if line:
            deny(f"Commit {sha[:9]} carries Claude attribution: \"{line}\".")


def check_github(data: dict) -> None:
    tool_input = data.get("tool_input", {})
    for key in ("title", "body", "commit_title", "commit_message"):
        line = offending(str(tool_input.get(key, "")))
        if line:
            deny(f"The {key} of this GitHub call carries Claude attribution: \"{line}\".")


def remind_after_create(data: dict) -> None:
    print(json.dumps({"hookSpecificOutput": {
        "hookEventName": "PostToolUse",
        "additionalContext": "The GitHub server can append a 'Generated by Claude Code' footer "
            "to a new pull request. Read the PR back now and, if a footer or session link was "
            "added, update the body to remove it."}}))


def main() -> None:
    data = json.load(sys.stdin)
    tool = data.get("tool_name", "")
    if data.get("hook_event_name") == "PostToolUse":
        if tool.endswith("create_pull_request"):
            remind_after_create(data)
        return
    if tool == "Bash":
        check_push(data)
    elif tool.startswith("mcp__github__"):
        check_github(data)


if __name__ == "__main__":
    main()
